### ISSUE TITLE
CPUグラフが正常に表示されない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/system-dashboard#2]
system_dashboard.py 249の変数を増やすと解決します。
ただし色を考えなければいけないどこまでサポートするかは検討が必要理想は自動で生成

ログ
  File "/home/naoko/system-dashboard/system_dashboard.py", line 305, in CPUGraphDraw
    util.SetRGB(ctx, Color[color_number])
IndexError: list index out of range

**Comment by mk-419** [comment]
685c4488f033795d363c32591f4814acbc4530c6 で色の自動生成に対応しました
